"""empty message

Revision ID: d54e09c02438
Revises: 
Create Date: 2021-06-21 21:30:50.291969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd54e09c02438'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('niveau', sa.String(length=64), nullable=True),
    sa.Column('chapitre', sa.String(length=128), nullable=True),
    sa.Column('sujet', sa.String(), nullable=True),
    sa.Column('contenu', sa.String(), nullable=True),
    sa.Column('commentaire', sa.String(), nullable=True),
    sa.Column('typologie', sa.String(), nullable=True),
    sa.Column('difficulte', sa.Integer(), nullable=True),
    sa.Column('annee', sa.Integer(), nullable=True),
    sa.Column('auteur', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercice')
    # ### end Alembic commands ###
